CREATE DATABASE IF NOT EXISTS EA_DATABASE;
USE EA_DATABASE;

DROP TABLE IF EXISTS RANDOM_FILES;

CREATE TABLE IF NOT EXISTS RANDOM_FILES(
    RANDOM_DATE DATE NOT NULL,
    LATIN_CHARS VARCHAR(10) NOT NULL,
    RUSSIAN_CHARS VARCHAR(10) NOT NULL,
    INTEGERS INT NOT NULL,
    DOUBLES DOUBLE NOT NULL
);

drop procedure if exists sum_and_median;

DELIMITER //
CREATE PROCEDURE sum_and_median(OUT sum BIGINT, OUT median DOUBLE)
BEGIN
	SELECT SUM(INTEGERS) AS SUM FROM RANDOM_FILES INTO sum;

    SET @rowindex := -1;
	SELECT
	   AVG(rf.DOUBLES)
	FROM
	   (SELECT @rowindex:=@rowindex + 1 AS rowindex,
			   RANDOM_FILES.DOUBLES AS DOUBLES
		FROM RANDOM_FILES
		ORDER BY RANDOM_FILES.DOUBLES) AS rf
	WHERE
	rf.rowindex IN (FLOOR(@rowindex / 2) , CEIL(@rowindex / 2))
    INTO median;
END
//

SELECT * FROM RANDOM_FILES order by doubles;
TRUNCATE TABLE  RANDOM_FILES;
